### PR TITLE
Package is now in a publishable state.

### PR DESCRIPTION
**Pull request by DavidBruant**
Moves #43 a step closer

### CODE REVIEW

**Comment by DavidBruant** [comment]
I'm happy to re-discuss the exposed API if necessary.

**Comment by gijsk** [comment]
I think we should only expose + require Readability.js from the package file. Ideally in N days/weeks/months from now we can ditch having jsdomparser in this repo (either it can be in its own repo or we can start relying on jsdom or whatever).

**Comment by DavidBruant** [comment]
Ok for having a document as argument.
I guess I'll make a request to change the API of mine as well. The uri argument should be a string, not the non-standard, non-obvious URI object.
I'll try to cook something from the `url` node module.

**Comment by pdehaan** [comment]
@DavidBruant,

Re: `url` node module, see https://github.com/mozilla/readability/issues/29. I wrote it quickly, but it may work (or maybe not, thats the fun of software!)

**Comment by gijsk** [comment]
This has conflicts and is superseded by #608, so I'm gonna close this out.

**Pull request closed without merging**
