### PR TITLE
Fixes #216 - Limit counted commas score.

### LINKED ISSUE #216: HTTP/2 spec shows only the appendix in reader mode
http://http2.github.io/http2-spec/

Filed from https://bugzilla.mozilla.org/show_bug.cgi?id=1162741

### PR DESCRIPTION
**Pull request by n1k0**
Refs #216; this patch limits the node score added by counting the commas it contains, allowing to balance the selection of the top candidate more wisely. This also slightly improves the results for other tests.

r=? @gijsk @leibovic

### CODE REVIEW

**Comment by gijsk** [comment]
Any particular reason for 60 as a maximum? :-)

**Comment by n1k0** [comment]
> Any particular reason for 60 as a maximum? :-)

Endless tweaking until everything passes. I know.

**Comment by n1k0** [comment]
A little more scientifically though, if you get a paragraph with more than 60 commas (which kinda stands for "a lot" here), you're more likely to face a long list of stuff, like in the http2 spec. A finer approach might be to use a number of words/number of commas ratio… Thoughts?

**Comment by n1k0** [comment]
> A finer approach might be to use a number of words/number of commas ratio…

Bah:

> Also, there is no “word-to-comma” ratio.

— http://www2.bakersfieldcollege.edu/gdumler/Engl%201A/Supplements/commas_semicolons_colons_periods.htm

**Comment by gijsk** [comment]
Seems like the entire comma thing is a bit dodgy, then... :-\

**Comment by gijsk** [comment]
Closing out old conflicting PRs.

**Pull request closed without merging**
