### PR TITLE
Remove reliance on inert nodecollection

### PR DESCRIPTION
**Pull request by gijsk**
This gets rid of the node collection stuff for the main loop, which should solve a lot of issues. The rest of the code (that uses getElementsByTagName) doesn't actually try to remove things from the array, so should be OK.

There are other things we can do now that the loop uses some more sane constructs and the DOM is more powerful, but I've held off on that for now.

This change in and of itself passes all our existing tests.

### CODE REVIEW

**Comment by gijsk** [comment]
(oh, and purely based on some totally unscientific tests in my console, it seems to be approximately 30% faster at running all our tests)

**Comment by gijsk** [comment]
@leibovic, @n1k0 thoughts/reviews? :-)

**Comment by leibovic** [comment]
@thebnich, can you take a look at these JSDOMParser changes?

**Comment by leibovic** [comment]
We discussed this in person, but for posterity: I think it's fine to merge this, since it's a strict improvement over what we currently have, and we can continue to hack on this tomorrow before merging things into fx-team.

**Comment by leibovic** [comment]
Aside: I wonder if it would be worth some simple unit tests for JSDOMParser. Maybe not, if we're going to move away from using this, but it could be nice to test the new node manipulation logic.

**Comment by gijsk** [comment]
Per IRL discussion, merging first, doing tests/checks later!

**Pull request merged**
