### PR TITLE
Adding package-lock.json

### PR DESCRIPTION
**Pull request by ankushduacodes**

### CODE REVIEW

**Comment by gijsk** [comment]
@ankushduacodes hey, thanks for this PR - can you elaborate on how you generated it (esp. from which commit - current master or a different one)? I tried to generate it myself and npm created a different file, and I'm not sure how to reconcile the differences and whether they matter...

**Comment by ankushduacodes** [comment]
@gijsk I rebased my forked repo with the current master repo and generated from it...

**Comment by gijsk** [comment]
OK, let's just assume this works. :-)

**Comment by danburzo** [comment]
I've just re-created package-lock.json from scratch to be sure, and the only difference is in eslint, which has seen a new release in the meantime. So, looks good to me!

**Comment by ankushduacodes** [comment]
@gijsk If you have any other issues that are beginners friendly, I would love to work on them.

**Pull request merged**
