### PR TITLE
Bug 1310074 - Tests for yahoo.com. r=Gijs

### PR DESCRIPTION
**Pull request by evanxd**
Hi @gijsk ,

I've added tests for yahoo.com, and they are all passed on Travis CI.
Could you help review the patch?

Thanks.

### CODE REVIEW

**Comment by gijsk** [comment]
This seems to have the same problem as the wikipedia patch (spacing gone missing).

**Comment by gijsk** [comment]
@evanxd , do you want to update this patch now that the wikipedia tests have landed?

**Comment by evanxd** [comment]
@gijsk ,

Sure, I've updated the patch to fix the space issues. And this is the [`source.html` page][source-page] from Yahoo.

Thanks for reviewing.

[source-page]: http://finance.yahoo.com/news/best-psvr-games-170003443.html

**Comment by gijsk** [comment]
Nice, thanks!

**Pull request merged**
