### PR TITLE
Fix issue #267 by ignoring hash URIs when making URIs absolute

### PR DESCRIPTION
**Pull request by gijsk**
@leibovic can you take a look? Should be a pretty trivial review - turns out there were some existing testcases where we mangled these URIs, but the guts of the change are visible through just looking at Readability.js, the base-url testcase, and the changes to test-readability.js.

### CODE REVIEW

**Comment by leibovic** [comment]
Good catch, this looks reasonable to me.

**Comment by leibovic** [comment]
@gijsk Will you make a patch to update Readability.js in m-c? What's our process been for updating that recently?

**Comment by gijsk** [comment]
> @gijsk Will you make a patch to update Readability.js in m-c? What's our process been for updating that recently?
Yeah, I'll just uplift to m-c when I find a moment. I don't think we have a particularly solid process - there haven't been that many m-c-related changes in the last year or thereabouts. m-c already has everything before this change, I believe?

**Comment by gijsk** [comment]
Heh, and now it turns out some folks changed readability in m-c because of eslint (bug 1245649). We might need more process. :-\

**Comment by rnewman** [comment]
Hurgh.

**Pull request merged**
