### PR TITLE
Fixes #81 - Keep article images.

### LINKED ISSUE #81: Some images are still erroneously stripped out from content
Test case: https://medium.com/backchannel/inside-the-deep-web-drug-lab-9718cd0fe504

Original:

```html
<figure name="c4e6" id="c4e6" class="graf--figure postField--fillWidthImage">
    <div class="aspectRatioPlaceholder is-locked">
        <div class="aspect-ratio-fill" style="padding-bottom: 66.8%;"></div>
        <img class="graf-image" data-image-id="1*4gN1-fzOwCniw-DbqQjDeQ.jpeg"
        data-width="2100" data-height="1402" src="https://d262ilb51hltx0.cloudfront.net/max/2000/1*4gN1-fzOwCniw-DbqQjDeQ.jpeg">
    </div>
    <figcaption class="imageCaption">Cristina Gil Lladanosa, at the Barcelona testing lab | photo by Joan Bardeletti</figcaption>
</figure>
```

Processed:

```html
<figure name="c4e6" id="c4e6" class="graf--figure postField--fillWidthImage">
    <figcaption class="imageCaption">Cristina Gil Lladanosa, at the Barcelona testing lab | photo by Joan Bardeletti</figcaption>
</figure>
```

### PR DESCRIPTION
**Pull request by n1k0**
Not super sure with this one, though that fixes #81 and doesn't break the rest of tests.

r? @leibovic @gijsk

### CODE REVIEW

**Comment by gijsk** [comment]
It seems like the basic idea here was to remove items which contain more images than paragraphs. I don't know why that'd be desirable. Has anyone looked at the archaeology here to figure out why?

**Comment by n1k0** [comment]
It was already there [in arc90's first released version](https://code.google.com/p/arc90labs-readability/source/browse/trunk/js/readability.js?spec=svn82&r=82#199). Hard to figure out what's the exact reasoning behind this…

**Comment by gijsk** [comment]
Hm. At the point where we remove the container, can we check if either it or its parent is a `<figure>` ? That would be a more conservative change and would also fix this issue.

**Comment by n1k0** [comment]
Good idea, will do.

**Comment by n1k0** [comment]
Now that's annoying, tests are green on my box while one of them breaks on Travis. Both envs are up to date. Oh dear.

**Comment by n1k0** [comment]
Ohh that's nice, only one of the two Travis builds is failing. That means intermittent I guess? Oh dear.

**Comment by n1k0** [comment]
Bah, that was just because I didn't rebase.

**Comment by gijsk** [comment]
\o/

**Pull request merged**
