### PR TITLE
Add iframe support for cdn.embedly.com in REGEXPS.videos

### PR DESCRIPTION
**Pull request by cayolblake**
This pull request adds support for extracting iframes with src from cdn.embedly.com which is common on many websites.

### CODE REVIEW

**Comment by gijsk** [comment]
Thank you for this PR! Do you think it'd be possible to add a testcase to verify this works?

**Comment by cayolblake** [comment]
Most welcomed. Planning to do some more soon.

About test cases, not sure how to do that, I can try if there're some sort of guide or a tutorial on doing so.

**Comment by gijsk** [comment]
You can run the [`generate-testcase.js`](https://github.com/mozilla/readability/blob/master/test/generate-testcase.js) script with `node` and pass it a slug (probably `embedly` would be a good one here) and a URL (to a test page) and it will fetch that page's HTML, run readability on it, and create all the files (though you'll need to `git add` them to a commit of course).

**Review by Niek — APPROVED** [review]

**Comment by cgorrieri** [comment]
I see this was opened for a while and more the reason to make this video regex configurable with a default value.
https://github.com/mozilla/readability/issues/787

**Pull request closed without merging**
