### PR TITLE
Refs #128 - Add support for options to Readability constructor.

### PR DESCRIPTION
**Pull request by n1k0**
Refs #128, WiP. 

The diff is super ugly, I'm sorry :(

Feedback=? @gijsk @leibovic

### CODE REVIEW

**Comment by gijsk** [comment]
How can I see the diff? I just get " 1,504 additions, 1,478 deletions not shown " and there doesn't seem to be a way to show them... :-\

**Comment by n1k0** [comment]
That's because I've wrapped the whole readability declaration within an IIFE. I'll try to come with a less invasive change.

**Comment by n1k0** [comment]
Much cleaner diff, though I really liked the IIFE approach. Oh well.

**Comment by gijsk** [comment]
LGTM, can you squash the commits before merging?

**Pull request merged**
