### PR TITLE
Clean <input>,<textarea>,<select>,<button> elements

### PR DESCRIPTION
**Pull request by gijsk**
This is also taken out of #313, but now includes two further changes:

1) ensure we don't remove divs inside `<figure>` even if they have only very little content, as this removes e.g. the text in the `<figcaption>` in one of the yahoo testcases.
2) fix tests

@evanxd, can you look at these changes and check they look OK to you?

CC @andrei-ch

### CODE REVIEW

**Comment by evanxd** [comment]
Looks like we want to clean `<form>` related tags. If so, why don't we also remove `<form>`, `<fieldset>`, and `<label>` tags here?

**Comment by evanxd** [comment]
And we need to fix `yahoo-3` test for this change.

**Comment by gijsk** [comment]
We already have code to remove `<form>` a bit higher up in the file. `<label>` seems like it's likely to be used outside forms (even though it probably shouldn't be). I agree that we can probably remove `<fieldset>`, so I can add support for that.

**Comment by evanxd** [comment]
Sure, let's add `<fieldset>` and merge it.

**Pull request merged**
